### This is a markdown (regular text, not code) --- testing markdown

###### Creating Arrays

In [1]:
import numpy as np

In [3]:
my_list1 = [1, 2, 3, 4]
my_array1 = np.array(my_list1)
my_array1

array([1, 2, 3, 4])

In [4]:
my_list2 = [11, 22, 33, 44, 55]

In [5]:
my_lists = [my_list1, my_list2]
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44, 55]]

In [6]:
my_array2 = np.array(my_lists)

In [7]:
my_array2

array([[1, 2, 3, 4], [11, 22, 33, 44, 55]], dtype=object)

In [9]:
my_array2.shape

(2,)

In [10]:
my_list2.pop()
my_list2

[11, 22, 33, 44]

In [11]:
my_listsX=[my_list1, my_list2]
my_listsX

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [12]:
my_array3 = np.array(my_listsX)
my_array3

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [13]:
my_array3.shape

(2, 4)

In [14]:
my_array2.dtype

dtype('O')

In [15]:
my_array3.dtype

dtype('int32')

In [18]:
type(my_array3)

numpy.ndarray

In [19]:
#special case arrays

In [20]:
my_zeros=np.zeros(5)

In [21]:
my_zeros

array([ 0.,  0.,  0.,  0.,  0.])

In [22]:
my_ones = np.ones([5,5])
my_ones

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [23]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [24]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [25]:
np.arange(3, 8)

array([3, 4, 5, 6, 7])

### Lecture 8

In [26]:
5/2

2.5

 ### lecture 9 --- indexing arrays

In [27]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr[8]

8

In [29]:
arr[1:5]

array([1, 2, 3, 4])

In [30]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [31]:
arr_slice = arr[3:7]

In [32]:
arr_slice

array([100, 100,   5,   6])

In [33]:
arr_slice[:] = 99
arr_slice

array([99, 99, 99, 99])

In [35]:
# to show that the original array is changed
arr

array([100, 100, 100,  99,  99,  99,  99,   7,   8,   9,  10])

In [36]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr2 = arr.copy()
arr2[0:5] = 100
arr2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr = np.arange(12)
arr
arr_2d = arr.reshape(3,4)
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
arr_2d[2][3]

11

In [46]:
arr_2d_slice = arr_2d[:2, 1:]
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
arr_2d_slice

array([[1, 2, 3],
       [5, 6, 7]])

In [49]:
arr_2d_element = arr_2d[2,2]

In [50]:
arr_2d_element

10

In [51]:
arr_2d[2][2]

10

In [52]:
### fancy indexing
arr3 = np.zeros(5)
arr3

array([ 0.,  0.,  0.,  0.,  0.])

In [54]:
arr3 = np.zeros([10, 10])  # has to be a list [10, 10] if two dimensions is wanted, rather than zeros(10, 10)
arr3

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [56]:
arr3.shape
arr3.shape[1]

10

In [57]:
arr3.shape

(10, 10)

In [58]:
arr3.shape[3]

IndexError: tuple index out of range

In [59]:
arr3.shape[0]

10

In [60]:
type(arr3.shape)

tuple

In [62]:
for i in range(arr3.shape[0]):
    arr3[i] = i
arr3

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [64]:
#fancy indexing
arr4 = arr3[[2,4,6,8,10, 12, 14, 16, 18, 20]]
arr4

IndexError: index 10 is out of bounds for axis 0 with size 10

In [65]:
arr4 = arr3[[2,4,6,8]]  # the numbers are the index 
arr4

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [66]:
arr3[:, 4] = 99
arr3

array([[  0.,   0.,   0.,   0.,  99.,   0.,   0.,   0.,   0.,   0.],
       [  1.,   1.,   1.,   1.,  99.,   1.,   1.,   1.,   1.,   1.],
       [  2.,   2.,   2.,   2.,  99.,   2.,   2.,   2.,   2.,   2.],
       [  3.,   3.,   3.,   3.,  99.,   3.,   3.,   3.,   3.,   3.],
       [  4.,   4.,   4.,   4.,  99.,   4.,   4.,   4.,   4.,   4.],
       [  5.,   5.,   5.,   5.,  99.,   5.,   5.,   5.,   5.,   5.],
       [  6.,   6.,   6.,   6.,  99.,   6.,   6.,   6.,   6.,   6.],
       [  7.,   7.,   7.,   7.,  99.,   7.,   7.,   7.,   7.,   7.],
       [  8.,   8.,   8.,   8.,  99.,   8.,   8.,   8.,   8.,   8.],
       [  9.,   9.,   9.,   9.,  99.,   9.,   9.,   9.,   9.,   9.]])

In [67]:
arr4 = arr3[[2,4,6,8]]  # the numbers are the index 
arr4

array([[  2.,   2.,   2.,   2.,  99.,   2.,   2.,   2.,   2.,   2.],
       [  4.,   4.,   4.,   4.,  99.,   4.,   4.,   4.,   4.,   4.],
       [  6.,   6.,   6.,   6.,  99.,   6.,   6.,   6.,   6.,   6.],
       [  8.,   8.,   8.,   8.,  99.,   8.,   8.,   8.,   8.,   8.]])